#--------------------------------------------
# Local Public Development Profile
#--------------------------------------------

magnolia.develop=true
magnolia.superuser.enabled=true
magnolia.utf8.enabled=true
magnolia.update.auto=true

# Bootstrap this repository as a public instance.
magnolia.bootstrap.authorInstance=false
magnolia.bootstrap.dir=WEB-INF/bootstrap/public WEB-INF/bootstrap/common
magnolia.bootstrap.samples=true

magnolia.webapp=Local Public
magnolia.server.defaultBaseUrl=http://localhost:8081
magnolia.repositories.jackrabbit.indexing.optimization=true
